language: python
python:
  - "3.5"

install:
  - "pip install pipenv"
  - "pip install codecov"
  - "pipenv install --dev --skip-lock"

script:
  - pipenv run pytest --cov=ors_subscribe_email tests

after_success:
  - codecov
